# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='DateMax',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='DateMin',
            field=models.DateTimeField(),
        ),
    ]
