# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ys', '0003_registration_accountid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='AccountID',
        ),
    ]
