# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ys', '0005_registration_accountid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='AccountID',
            field=models.CharField(default='', max_length=128),
        ),
    ]
