# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ys', '0008_auto_20170202_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontable',
            name='User',
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='Transaction_Amount',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='Transaction_Description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='Transaction_Type',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='Transaction_status',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='Transaction_weight',
            field=models.CharField(default='', max_length=10),
        ),
    ]
