# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ys', '0009_auto_20170202_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='Transaction_Amount',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transactiontable',
            name='Transaction_Description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='transactiontable',
            name='Transaction_Type',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='transactiontable',
            name='Transaction_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transactiontable',
            name='Transaction_status',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='transactiontable',
            name='Transaction_weight',
            field=models.CharField(max_length=10),
        ),
    ]
